<?php

use Drupal\car_partners\PartnerRelations;

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @param  \Drupal\Core\Entity\EntityInterface  $node
 *
 */
function car_partners_node_update(Drupal\Core\Entity\EntityInterface $node) {
  PartnerRelations::ManagePartnerRelations($node);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param  \Drupal\Core\Entity\EntityInterface  $node
 *
 */
function car_partners_node_insert(Drupal\Core\Entity\EntityInterface $node) {
  PartnerRelations::ManagePartnerRelations($node);
}
