<?php

/**
 * @file
 * Provides two custom Webform composite elements for item metadata for vendor.
 */

module_load_include('inc', 'webform', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function webform_car_ip_data_for_vendor_theme() {
  return [
    'webform_car_ip_data_for_vendor' => [
      'render element' => 'element',
    ],
    'car_print_data_for_vendor' => [
      'render element' => 'element',
    ],
    'car_related_material' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for item part data for vendor templates.
 *
 * Default template: webform-car-ip-data-for-vendor.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_car_ip_data_for_vendor(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}

/**
 * Prepares variables for print item data for vendor templates.
 *
 * Default template: car-print-data-for-vendor.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_car_print_data_for_vendor(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}

/**
 * Prepares variables for related material templates.
 *
 * Default template: car-related-material.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_car_related_material(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}
