version: '3.5'
# Add additional image for development. Has Xdebug and more logging enabled.
# Changes default Config for Ngnix to map based on Xdebug cookie
# See inside ${PWD}/xdebug/jsbookmarks-for-xdebug.txt for bookmarks that can be used
# as Bookmark elements in your Browser to set/unset the cookie that triggers the
# mapping between esmero-php-debug and esmero-php
services:
  web:
    container_name: esmero-web
    restart: always
    image: "nginx"
    depends_on:
      - solr
      - php
    tty: true
    ports:
      - "8001:80"
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}/nginxconfigford8/xdebug.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}:/var/www/html:cached
  php-debug:
    container_name: esmero-php-debug
    restart: always
    image: esmero-php:development
    tty: true
    networks:
      - host-net
      - esmero-net
    volumes:
      - ${PWD}:/var/www/html:cached
